### ISSUE TITLE
MongoDB caching

### ISSUE THREAD

**Issue by Xharos** [islands-wars/commons#3]
### Description

Add mongodb service connection implementation.

Use GSON serializer to dynamically load object

**Comment by Xharos** [comment]
Test with :
```yml
version: '3.9'

services:

  mongo:
    image: mongo:4.0.4
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongodb
```
